services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: secure_tasks
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: secure_tasks
      NODE_ENV: development
    depends_on:
      - db

volumes:
  db_data: